[package]
name = "makepad-analyzer"
description = "Makepad LSP server"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
makepad-analyzer-server.workspace = true
clap = { workspace = true, features = ["derive"] }
